# Site settings
title: PHLDesign Co.
tagline: "Philadelphia Community of Web Designers and Devs"
url: "http://phldesign.co"
timezone: America/New_York

# Social
twitter: atn1988
socialimg: /img/social.jpg

# Contact
phone: "215-834-4413"
email: "hi@antnguyen.com"

# Use this for production
#sass:
#    style: :compressed

exclude: [README.md, node_modules, gruntfile.js, package.json]

markdown: kramdown

excerpt_separator: ""

gems: [jekyll-admin]
# This will require each of these gems automatically.